import React, { useState } from 'react';
import { 
  LayoutDashboard, 
  Bookmark, 
  Clock, 
  CheckCircle2, 
  AlertCircle, 
  Trash2, 
  ExternalLink,
  FileDown,
  Sparkles,
  ArrowRight
} from 'lucide-react';
import { BIS_STANDARDS } from '../data/bisKnowledgeBase';

interface DashboardProps {
  onNavigate: (tab: string) => void;
}

export const Dashboard: React.FC<DashboardProps> = ({ onNavigate }) => {
  const [checklist, setChecklist] = useState({
    identifiedIS: true,
    qcoVerified: true,
    sitTestingEquip: false,
    staffTrained: true,
    manakRegistered: false,
  });

  const [savedStandards, setSavedStandards] = useState<string[]>([
    'std-17526', // IS 17526:2021 Water Bottle
    'std-2347',  // IS 2347:2017 Pressure Cooker
    'std-4151'   // IS 4151:2015 Helmet
  ]);

  // Calculate readiness score
  const totalItems = Object.keys(checklist).length;
  const completedItems = Object.values(checklist).filter(Boolean).length;
  const readinessScore = Math.round((completedItems / totalItems) * 100);

  const toggleCheck = (key: keyof typeof checklist) => {
    setChecklist(prev => ({ ...prev, [key]: !prev[key] }));
  };

  const handleRemoveSaved = (id: string) => {
    setSavedStandards(prev => prev.filter(s => s !== id));
  };

  const handleExportReport = () => {
    const reportText = `BIS SAHAYAK AI - COMPLIANCE READINESS AUDIT\nDate: ${new Date().toLocaleDateString()}\nReadiness Score: ${readinessScore}%\n\nStatus:\n- Identified Standard: ${checklist.identifiedIS ? 'DONE' : 'PENDING'}\n- QCO Legal Verification: ${checklist.qcoVerified ? 'DONE' : 'PENDING'}\n- In-house Lab Equipment & SIT: ${checklist.sitTestingEquip ? 'DONE' : 'PENDING'}\n- Quality Testing Personnel: ${checklist.staffTrained ? 'DONE' : 'PENDING'}\n- Manakonline Portal Registration: ${checklist.manakRegistered ? 'DONE' : 'PENDING'}\n\nTracked Standards:\n${savedStandards.map(id => {
      const s = BIS_STANDARDS.find(std => std.id === id);
      return `- ${s?.standardNumber}: ${s?.title}`;
    }).join('\n')}\n\nDisclaimer: Informational audit checklist generated by BIS Sahayak AI.`;

    const blob = new Blob([reportText], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `BIS_Compliance_Readiness_${Date.now()}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-8 space-y-8">
      
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 border-b border-slate-200 pb-6">
        <div>
          <div className="flex items-center gap-2">
            <h1 className="text-2xl font-bold text-slate-900 tracking-tight">
              Manufacturer &amp; MSME Compliance Dashboard
            </h1>
            <span className="text-[10px] bg-bis-blue/10 text-bis-blue font-bold px-2 py-0.5 rounded">
              SIH 26107
            </span>
          </div>
          <p className="text-xs sm:text-sm text-slate-600 mt-1">
            Track saved Indian Standards, evaluate application readiness, and export compliance reports.
          </p>
        </div>

        <button
          onClick={handleExportReport}
          className="px-4 py-2 rounded-xl bg-slate-900 hover:bg-slate-800 text-white text-xs font-semibold flex items-center gap-2 transition-colors shadow-xs"
        >
          <FileDown className="w-4 h-4" />
          <span>Export Audit Summary</span>
        </button>
      </div>

      {/* Compliance Readiness Score Card */}
      <div className="bg-bis-navy text-white rounded-2xl p-6 sm:p-8 shadow-md border border-bis-blue/40">
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-center">
          
          <div className="lg:col-span-4 text-center sm:text-left space-y-2">
            <span className="text-xs font-bold text-bis-slate uppercase tracking-wider">
              Audit Readiness Index
            </span>
            <div className="flex items-baseline gap-2 justify-center sm:justify-start">
              <span className="text-5xl font-black font-mono text-emerald-400">
                {readinessScore}%
              </span>
              <span className="text-xs text-slate-400">Readiness Score</span>
            </div>
            <p className="text-xs text-slate-300 leading-relaxed pt-1">
              {readinessScore >= 80 
                ? 'High Readiness: You are positioned well to file Form-I on Manakonline.'
                : 'In Progress: Complete remaining laboratory and testing preparations before inviting inspection.'}
            </p>
          </div>

          <div className="lg:col-span-8 bg-white/10 p-5 rounded-xl backdrop-blur-xs space-y-3">
            <h3 className="text-xs font-bold uppercase tracking-wider text-bis-slate">
              Statutory Prerequisites Checklist (Click to Toggle):
            </h3>
            
            <div className="space-y-2 text-xs">
              {[
                { key: 'identifiedIS', label: 'Applicable Indian Standard verified with latest amendments' },
                { key: 'qcoVerified', label: 'Quality Control Order (QCO) gazette deadline checked' },
                { key: 'sitTestingEquip', label: 'In-house test equipment installed & calibrated per SIT guidelines' },
                { key: 'staffTrained', label: 'Dedicated testing chemist/personnel certified on test methods' },
                { key: 'manakRegistered', label: 'Enterprise profile & Form-I initiated on manakonline.in' },
              ].map((item) => {
                const checked = checklist[item.key as keyof typeof checklist];
                return (
                  <label 
                    key={item.key}
                    onClick={() => toggleCheck(item.key as keyof typeof checklist)}
                    className="flex items-center gap-3 p-2 rounded-lg hover:bg-white/10 cursor-pointer transition-colors"
                  >
                    <input 
                      type="checkbox" 
                      checked={checked} 
                      readOnly 
                      className="w-4 h-4 rounded text-bis-blue focus:ring-0 accent-bis-blue"
                    />
                    <span className={checked ? 'text-white font-medium' : 'text-slate-400 line-through'}>
                      {item.label}
                    </span>
                  </label>
                );
              })}
            </div>
          </div>

        </div>
      </div>

      {/* Saved Standards Section */}
      <div className="space-y-4">
        <div className="flex items-center justify-between">
          <h2 className="text-lg font-bold text-slate-900 flex items-center gap-2">
            <Bookmark className="w-4 h-4 text-bis-blue" />
            <span>Tracked &amp; Bookmarked Standards ({savedStandards.length})</span>
          </h2>
          <button
            onClick={() => onNavigate('finder')}
            className="text-xs font-semibold text-bis-blue hover:text-bis-blue-hover flex items-center gap-1"
          >
            <span>Discover More Standards</span>
            <ArrowRight className="w-3.5 h-3.5" />
          </button>
        </div>

        {savedStandards.length === 0 ? (
          <div className="p-8 bg-white border border-slate-200 rounded-2xl text-center text-xs text-slate-500">
            No standards bookmarked yet. Search standards to pin them to your dashboard.
          </div>
        ) : (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
            {savedStandards.map((stdId) => {
              const std = BIS_STANDARDS.find(s => s.id === stdId);
              if (!std) return null;

              return (
                <div 
                  key={std.id}
                  className="bg-white rounded-xl border border-slate-200 p-4 shadow-xs hover:shadow-md transition-all flex flex-col justify-between"
                >
                  <div className="space-y-2">
                    <div className="flex items-center justify-between">
                      <span className="text-xs font-mono font-bold text-bis-blue bg-bis-blue/10 px-2.5 py-0.5 rounded border border-bis-blue/20">
                        {std.standardNumber}
                      </span>
                      <button
                        onClick={() => handleRemoveSaved(std.id)}
                        className="text-slate-400 hover:text-red-600 p-1 rounded transition-colors"
                        title="Remove bookmark"
                      >
                        <Trash2 className="w-3.5 h-3.5" />
                      </button>
                    </div>

                    <h3 className="text-sm font-bold text-slate-900 line-clamp-2">
                      {std.title}
                    </h3>

                    <p className="text-xs text-slate-600 line-clamp-2">
                      {std.scopeSummary}
                    </p>
                  </div>

                  <div className="mt-4 pt-3 border-t border-slate-100 flex items-center justify-between text-xs">
                    <span className={`text-[10px] font-bold px-2 py-0.5 rounded ${
                      std.qcoMandatory ? 'bg-red-50 text-red-800' : 'bg-slate-100 text-slate-700'
                    }`}>
                      {std.qcoMandatory ? 'MANDATORY QCO' : 'Voluntary'}
                    </span>

                    <a
                      href={std.sourceUrl}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="text-bis-blue hover:text-bis-blue-hover font-medium inline-flex items-center gap-1"
                    >
                      <span>Manakonline</span>
                      <ExternalLink className="w-3 h-3" />
                    </a>
                  </div>
                </div>
              );
            })}
          </div>
        )}
      </div>

    </div>
  );
};
